<a href="https://colab.research.google.com/github/Thapanee633020670-2/python_dataviz2023/blob/main/Homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#HW2 สร้างโลโก้พรรคก้าวไกล

In [36]:
import numpy as np
OR = np.zeros((7,9))
#เหลี่ยมนอก
OR[0:1] = 7
OR[1,7:8] = 7
OR[2,6:7] = 7
OR[3,5:6] = 7
OR[4,4:5] = 7
OR[5,3:4] = 7
OR[6,2:3] = 7
#เหลี่ยมใน
OR[2,0:5] = 7
OR[3,3:4] = 7
OR[4,2:3] = 7
OR[5,1:2] = 7
OR[6,0:1] = 7
print(OR)


[[7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [0. 0. 0. 0. 0. 0. 0. 7. 0.]
 [7. 7. 7. 7. 7. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 7. 0. 0. 0. 0.]
 [0. 7. 0. 7. 0. 0. 0. 0. 0.]
 [7. 0. 7. 0. 0. 0. 0. 0. 0.]]


#HW 2.5
สร้าง Function เพื่อ print logo พรรคก้าวไกล โดย input พื้นหลังได้

In [38]:
import numpy as np

OR = np.ones((7, 9), dtype=str)
#เหลี่ยมนอก
OR[0:1] = 7
OR[1,7:8] = 7
OR[2,6:7] = 7
OR[3,5:6] = 7
OR[4,4:5] = 7
OR[5,3:4] = 7
OR[6,2:3] = 7
#เหลี่ยมใน
OR[2,0:5] = 7
OR[3,3:4] = 7
OR[4,2:3] = 7
OR[5,1:2] = 7
OR[6,0:1] = 7
OR[OR == "1"] = "Q"
print(OR)


[['7' '7' '7' '7' '7' '7' '7' '7' '7']
 ['Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q' '7' 'Q']
 ['7' '7' '7' '7' '7' 'Q' '7' 'Q' 'Q']
 ['Q' 'Q' 'Q' '7' 'Q' '7' 'Q' 'Q' 'Q']
 ['Q' 'Q' '7' 'Q' '7' 'Q' 'Q' 'Q' 'Q']
 ['Q' '7' 'Q' '7' 'Q' 'Q' 'Q' 'Q' 'Q']
 ['7' 'Q' '7' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q']]
